package com.henry.gem.inner;

public class Map {
	
	public static String[][] maps = {
			//Level 1
			{
				"b b b b b b 0 1 2 3 b b b b b",
				"b a a a a a a b a a b a a l b",
				"b a a p a a a a a a a a e b b",
				"b b b b b b a a a a b b b b b",
				"a a a a a a a a a b a a x a a",
				"a a a a a a b b b a a a a a a",
				"a a a a a a a a a a a a a a a",
				"a a a b a a b b b a a b a a a",
				"a a a b a a a b a 4 a b a a a",
				"a a a b b b b b b b b b a a a",
				"a a a a a a a a a a a a a a a",
				"a a x a a a e a a a e a c a a",
				"b a b a b a b b b a b b b a b",
				"a a a a a a a a a a a a a a a",
				"b b b b b b b b b b b b b b b"
			},
			
			//Level 2
			{
				"e",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"b b b b",
				"b p a a a a a a a a a a e a a",
				"b b b b a b b b a a b b b b b",
				"a a a b a b a b a a b a b a b",
				"b b b b a b b b b a b a b a b",
				"a a a a a a a a a a a a a a a",
				"b b b b b b b b b b b b b b b",
				"a a a a a a b a a a a a a a a",
				"a a a a a a a a a a a a a a a",
				"b a a a a a a a a b a a a a a",
				"a a a b a a a a a a a a a a a",
				"a a a a a a a a a a a a b a a",
				"a a a a a a b a a a a a a a a",
				"a a a a a a a a a a a a a a a",
				"a a a a a a a a a a a a b a a",
				"a a a a a a a a a a a a a a a",
				"a a a b a a a x a b a a a a a",
				"a a a a a a a b a a a a a b a"
			},
			
			//Level 3
			{
				"b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b",
				"b a a e a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a x b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a 4 a a a a a a a b",
				"b a a a a a a a a a a b b b b a a a a b b b a a a a a a a a a b b b a a a a a a b",
				"b b b b b b b b a a a a a a a a a a a a a a a a a a a b a a a a a a a a a b b b b",
				"b a a a a a a a a a a a a a a a b b b a a a a a a a a a b a a a a a a a a a a a b",
				"b a a a a a a a a a a a a a a a a a a a a a a b b b a a a b a a a a a a a a e a b",
				"b a a a a a a a b b b b b b b b a a a a a a a a a a a a a a b 0 a a a a a a a a b",
				"b a a a b b b a a a a a a a a a a a a a a a a a a a a a a a a b 0 a a a a b b b b",
				"b a a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a b e a a a a a a b",
				"b a a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a a b a a a a a a b",
				"b 3 a a b b a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a a a a a b",
				"b a a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a a a a b",
				"b a a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a a a b",
				"b b b a a a a a a a a a a a 3 3 3 e c a a c a a a a a a a a a a a a a a a b a a b",
				"b a a a a b a a a a a a a a b b b b b b b b b b b a a a a a a a a a a a a e b a b",
				"b 2 a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a a b b b b b b a b",
				"b b b b b b b b b b b a a a a a a a a a a a a a e a a a a a a a a a a a a a a a b",
				"b a a a a a a a a a a a a a a b b b b b b b b b b b b b b a a b b a a a a a a b b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b",
				"b b b a a b b b a a a b b b a a a a a a a a a a a a a a a b b a a a a a a a a a b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a b",
				"b a a a a a a a b b b a a a a a a a a a a a a a a a a b b a a a a a a a a a a a b",
				"b b b a a a a a a a a a a a a a a a a a a a a a a 2 2 a a a a a a a a a a a a b b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a b b a a a a a a a a a a a a a b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a b",
				"b b b a a a a a a a a a a a a a a a a a a a a b b a a b b a a a a a a a a a a a b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b b",
				"b a b b b b a a a a a a a a a a a a a a a b b a a a a a a b b a a a a a a a a a b",
				"b a a a a a a a 1 1 a a a a a a a a a a a a a a a a a a a a a a a a a a a a b a b",
				"b a a a a a a b b b b a a a a a a a a a a a a a a a a a a a a b b a a a a a a a b",
				"b a a a a a a e a a a a a l a a a a a a a a a a a a a a a a a a a a a a a a a b b",
				"b a a a a a a a a a a b b l a a a a a a a a a a a a a a a a a a a b b a a a a a b",
				"b a a a a b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b b a b",
				"b p a a a b a a a a a a a a a a a a b a a a b a a a a b a a a a b a a a a b b a b",
				"b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b"
			},
			
			//Level 4
			{
				"p b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b a b",
				"b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a b a a",
				"a a a b a a a b a a a b a a a b a a a b a a a b a a a b a a a b a a a b a a a b a a a b a a a b",
				"a a a a b a a a a b a a a a b a a a a b a a a a b a a a a b a a a a b a a a a b a a a a b a a a",
				"a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a",
				"b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b",
				"x a a a b b b b b b b b b b b b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b",
				"b b b a b b b b b b b b b b b b b b b a b b b b a b b b b a b b b b a b b b b a b b b b a b b b",
				"b b b a b b b b b b b b b b b b b b b a b a a b b b a a b a b b b b a b b b b b b b b b b b b b",
				"b a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b",
				"b a a b b b b b b b b b b b b b b b b b b a a b b b b b b b b b b b b b b b b b b b b b b b b b",
				"b a a b b b b b b b b b b b b b b b b b b a b b b b b b b b b b b b b b b 4 b b b 4 b a b a b a",
				"b a a a a a a a a a a a a a a a a a a a a e a a a a a a a a a a a a a a a a a a a a a c a c a c",
				"b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b"
			},
			
			//Level 5
			{
				"p",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"x",
				"b"
			}
	};

}